### ISSUE TITLE
Plant UML diagram not displayed in demo.

### ISSUE THREAD

**Issue by a-cordier** [Zenika/adoc-presentation-model#1]
Hi,

Just noticed that the plant UML diagram is not displayed in the demo.

Platform: POP OS (ubuntu)
Browser: Chrome 72*

Message:

Refused to apply style from 'https://bcouetil.gitlab.io/academy/sample/reveal/plugin/title-footer/title-footer.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by bcouetil** [comment]
Hey ! Thanks, sorry for the delay, I just transferred ownership to Zenika and forgot to watch it.

I'm checking the issue.

**Comment by bcouetil** [comment]
I have no problem whatsoever on Windows with Chrome, Opera, Firefox. I'll ask some friends under Linux to see if we can reproduce.

**Comment by bcouetil** [comment]
Precision : I have the title-footer.css error too. This is not an issue, the CSS is not used (and has never been). I'm correcting this for next version to not have the message in console 😉

**Comment by bcouetil** [comment]
Just checked on Ubuntu, it's working.

Closing, feel free to come back if any problem.
